GRANT ALL PRIVILEGES ON *.* TO `userradio`@`localhost` IDENTIFIED BY PASSWORD '*F1BDBDD712B9CEC71460890E89DF696E1D784946' WITH GRANT OPTION;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `radio`.* TO `userradio`@`localhost`;